### ISSUE TITLE
 d1-weather-station

### ISSUE THREAD

**Issue by Thomas1305** [skx/esp8266#20]
Hi Steve,
can´t find your weather station code.
Can you pls upload it. Thx.
Thomas

**Comment by skx** [comment]
Since I didn't write it, just used it, I didn't feel right leaving it in _this_ repository. That said you can extract the files because they used to be here, so this link will send you to the final version I had before I removed it:

* https://github.com/skx/esp8266/tree/30cbd992ab5278682a3fa5397142b4ba0fd482e8/d1-weather-station

As I said I didn't write it, and you can find the original link here to the source I took and (lightly) modified:

* https://github.com/ThingPulse/esp8266-weather-station

That's a better place to look because it has received updates and fixes since I copied/pasted their code.
