### ISSUE TITLE
12 hour time

### ISSUE THREAD

**Issue by pterodyne** [skx/esp8266#21]
I realize this is a flame worthy request.  But is there an easy way to convert this project, or have a setting that shows the time in 12 hour time instead of 24?  I realize there is no way to do AM or PM indicator, but that is easy to infer.  It's because we are using this clock in the house, and I want my young daughter to read it easier.  Great project by the way!  I love it's simplicity.  Prior I had been using an Raspberry Pi and an LCD, but this is way better.  Either way, thanks for your contribution.

**Comment by skx** [comment]
You don't link to a specific project, and this repository contains several.  But that said, yes it would be a pretty simple change to make.

Take the simplest one [d1-ntp-clock](https://github.com/skx/esp8266/tree/master/d1-ntp-clock) that project just gets the time (+date) via NTP and draws it on a set of 7-segment displays.

So what's the difference between a 12 hour clock, and a 24 hour clock?  Pretty much just the "hour" is 0-11  vs 0-23.  If you look at the code in that project this is the important part:

* [d1-ntp-clock.ino](https://github.com/skx/esp8266/blob/98ed673e31852aff1b2be9652884f3ff223f9bc5/d1-ntp-clock/d1-ntp-clock.ino#L210)

That code says:


      int cur_hour = timeClient.getHours();
      int cur_min  = timeClient.getMinutes();

Right now the time in Helsinki is 18:41.  You want to show "6:41" instead.  How do you do that?  Something like:

      if ( current_hour > 12 ) 
          current_hour -= 12;

Job done.

Of course you could use a modulus operation, or something else.  But I think that's a simple enough explaination - and because I test for >12 it means we go:

* 10:14
* 11:14
* 12:14  - i.e quarter past noon.
* 1:14   -  i.e. 1pm

With the change I guess you'd have "00:14" for "almost quarter past midnight".  I'll hope your daughter is asleep at that time of the day ;)

**Comment by pterodyne** [comment]
Sorry, about posting the issue in the wrong place.  New to Github.  Thanks for the reply.  it's still morning here but the code uploaded fine as:

```
    //
    // Get the current hour/min
    //
    int cur_hour = timeClient.getHours();
    int cur_min  = timeClient.getMinutes();
    
    if ( cur_hour > 12 ) 
    cur_hour -= 12;
```

**Comment by skx** [comment]
Great; I'll close this then.  If you have any problems / further questions do feel free to open additional issues.

(You filed in the right place, but since there are multiple projects in one repository it is more clear if you're explicit about which one you're asking about.)
