### ISSUE TITLE
Feature request -> Method to change for DST (d1-ntp-clock)

### ISSUE THREAD

**Issue by pterodyne** [skx/esp8266#22]
I don't have the skill but figured Id ask here.  Can you think of a way to have this project change for Daylight savings time automatically and switch back when it's over?  Right now I have to change the code and re-upload.  I've given a few of these away, and I always have to update for these people LOL.  Ideally we just remove Daylight savings time as a country.  I suspect that is harder than changing the code here.

Anyway thanks!

**Comment by skx** [comment]
I apologize for the slow reply; once upon a time I looked at this but decided that the simpler approach was just to handle it in my UI.

That works for me because I tend to have a HTTP-server on my projects, and I can let the user change things via a web-browser.  It might be that's overkill for you, but it was simple to use an update like this to change the offset:

        // Update the offset.
        timeClient.setTimeOffset(time_zone_offset * (60 * 60));
        timeClient.forceUpdate();

So I change from "2" to "3", locally.  And then it all just works.  (The [d1-helsinki-tram-times.ino](https://github.com/skx/esp8266/blob/master/d1-helsinki-tram-times/d1-helsinki-tram-times.ino) project has a bunch of code for doing that kind of thing - running as a HTTP-server, saving state to files, and changing the timezone on change.)

I did have a quick google and see other people have done this properly but right now I've not got any spare hardware to experiment & test with.  So regrettably I'll have to leave this open.
